apiVersion: apps/v1
kind: Deployment
metadata:
  name: java-app-deployment
  namespace: dina
spec:
  replicas: 2
  selector:
    matchLabels:
      app: java-app
  template:
    metadata:
      labels:
        app: java-app
    spec:
      containers:
      - name: java-app
        image: dinakhaled123/java-app:df83cc00773279b2520f1032292b09ea9cca53c4
        ports:
        - containerPort: 8090