apiVersion: apps/v1
kind: Deployment
metadata:
  name: java-app-deployment
  namespace: dina
spec:
  replicas: 2
  selector:
    matchLabels:
      app: java-app
  template:
    metadata:
      labels:
        app: java-app
    spec:
      containers:
      - name: java-app
        image: dinakhaled123/java-app:7b6d27d90440391e7eb2fa80ef4f3053bfc7485d
        ports:
        - containerPort: 8090