apiVersion: apps/v1
kind: Deployment
metadata:
  name: java-app-deployment
  namespace: dina
spec:
  replicas: 2
  selector:
    matchLabels:
      app: java-app
  template:
    metadata:
      labels:
        app: java-app
    spec:
      containers:
      - name: java-app
        image: dinakhaled123/java-app:401ffc6d84ee3293a170acc2aa1e1c2c02b03d40
        ports:
        - containerPort: 8090